spring.application.name=pg-spring

# JWT
jwt.secret=${JWT_SECRET:VQ7yTeEx\=Ko4vf56i+FpkLpbvdsVgzlU1vwk9To1o+yTE/O+xCSI\=coz+GuPP3ah3f6Sg4ghXQOeV61Xppqy6sktwEpA7}

# JPA

spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
spring.jpa.show-sql=${SPRING_JPA_SHOW_SQL:true}
spring.sql.init.mode=${SPRING_SQL_INIT_MODE:always}

#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# DATASOURCE (TiDB)
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://gateway01.ap-southeast-1.prod.aws.tidbcloud.com:4000/test}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:2NgxoF6YfPNB19q.root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:OUF3hby6ejMIORlx}

spring.cache.type=redis
spring.data.redis.host=${SPRING_DATA_REDIS_HOST:localhost}
spring.data.redis.port=${SPRING_DATA_REDIS_PORT:6379}
spring.data.redis.username=${SPRING_DATA_REDIS_USERNAME:khushbu}
spring.data.redis.password=${SPRING_DATA_REDIS_PASSWORD:#08.kcMA10}
spring.data.redis.ssl.enabled=false

# minio
minio.url=${MINIO_URL:http://minio:9000}
minio.access.name=${MINIO_ACCESS_NAME:minioadmin}
minio.access.secret=${MINIO_ACCESS_SECRET:minioadmin}
minio.bucket=${MINIO_BUCKET:pg-management}

logging.level.org.hibernate=WARN
logging.level.com.zaxxer.hikari=WARN
logging.level.io.github.newhoo.mysql.explain=OFF
